export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="h-[100dvh] overflow-hidden p-3 lg:p-4">
      <div className="grid h-full gap-3 lg:grid-cols-[minmax(0,1.08fr)_32rem]">
        <section className="surface-dark relative hidden min-h-0 overflow-hidden rounded-[2.25rem] px-8 py-8 lg:flex lg:flex-col xl:px-10 xl:py-10">
          <div
            aria-hidden="true"
            className="pointer-events-none absolute inset-0"
            style={{
              background: `
                radial-gradient(circle at 16% 18%, rgba(20, 115, 230, 0.22) 0%, transparent 34%),
                radial-gradient(circle at 82% 14%, rgba(255, 122, 69, 0.18) 0%, transparent 28%),
                radial-gradient(circle at 70% 78%, rgba(12, 155, 115, 0.16) 0%, transparent 24%)
              `,
            }}
          />

          {/* Brand header — pinned top */}
          <div className="relative z-10 shrink-0">
            <div className="flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-accent shadow-[0_18px_30px_rgba(20,115,230,0.26)]">
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
                    <path d="M8 1.5a1 1 0 0 1 1 1v2a1 1 0 0 1-2 0v-2a1 1 0 0 1 1-1ZM4.22 3.22a1 1 0 0 1 1.414 0l1.414 1.414a1 1 0 0 1-1.414 1.414L4.22 4.634a1 1 0 0 1 0-1.414ZM2.5 7a1 1 0 0 1 1-1h2a1 1 0 1 1 0 2h-2a1 1 0 0 1-1-1ZM14.5 7a1 1 0 0 1-1 1h-2a1 1 0 1 1 0-2h2a1 1 0 0 1 1 1ZM8 11.5a1 1 0 0 1 1 1v2a1 1 0 1 1-2 0v-2a1 1 0 0 1 1-1Z" fill="white"/>
                  </svg>
                </div>
                <div>
                  <p className="text-base font-semibold tracking-[-0.03em] text-sidebar-foreground">AxonVoice</p>
                  <p className="text-xs text-sidebar-muted">Tenant operations console</p>
                </div>
              </div>
              <span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-[0.62rem] font-medium uppercase tracking-[0.16em] text-sidebar-muted">
                Self-hosted
              </span>
            </div>
          </div>

          {/* Hero copy — fills remaining vertical space, vertically centered */}
          <div className="relative z-10 flex flex-1 flex-col justify-center py-8">
            <p className="eyebrow text-accent-warm">Production UX</p>
            <h1 className="mt-4 text-[2.6rem] font-semibold leading-[0.95] tracking-[-0.07em] text-sidebar-foreground lg:text-[3rem] xl:text-[3.4rem] 2xl:text-[3.85rem]">
              Multilingual voice operations without the dashboard noise.
            </h1>
            <p className="mt-5 max-w-lg text-sm leading-7 text-sidebar-muted xl:text-[0.94rem] xl:leading-8">
              Configure agents, protect tenant secrets, and move from setup to live traffic with a console that feels deliberate, not autogenerated.
            </p>
            <div className="mt-6 flex flex-wrap gap-2">
              {['Sinhala', 'Tamil', 'English', 'RAG-backed', 'Tenant-isolated'].map((item) => (
                <span
                  key={item}
                  className="rounded-full border border-white/10 bg-white/[0.05] px-3.5 py-2 text-sm font-medium text-sidebar-foreground/92"
                >
                  {item}
                </span>
              ))}
            </div>
          </div>

          {/* Bottom cards — pinned bottom, visible from lg up */}
          <div className="relative z-10 shrink-0 grid gap-4 lg:grid-cols-[1fr_0.9fr]">
            <div className="rounded-[1.8rem] border border-white/8 bg-white/[0.05] p-5 backdrop-blur-sm">
              <p className="eyebrow text-sidebar-muted/76">Why operators trust it</p>
              <ul className="mt-4 grid gap-3">
                {[
                  'Session tokens stay server-side in an HttpOnly cookie.',
                  'Gemini keys are stored encrypted and never re-exposed.',
                  'Agent setup, language rules, and rollout steps stay visible in one place.',
                ].map((item) => (
                  <li key={item} className="flex items-start gap-3 text-sm leading-6 text-sidebar-foreground/92">
                    <span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-accent-warm" />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="rounded-[1.8rem] border border-white/8 bg-black/16 p-5 backdrop-blur-sm">
              <p className="eyebrow text-sidebar-muted/76">Launch runway</p>
              <div className="mt-4 space-y-3">
                {[
                  ['01', 'Provision tenant workspace'],
                  ['02', 'Store BYOK Gemini credential'],
                  ['03', 'Ship the first voice contract'],
                ].map(([step, label]) => (
                  <div key={step} className="flex items-center gap-3 rounded-2xl bg-white/[0.04] px-4 py-3 text-sm text-sidebar-foreground/92">
                    <span className="font-mono text-xs text-accent-warm">{step}</span>
                    <span>{label}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section className="relative flex min-h-0 items-center justify-center overflow-hidden rounded-[2.25rem] px-0 py-0 sm:px-4 sm:py-4 lg:px-6">
          <div
            aria-hidden="true"
            className="pointer-events-none absolute inset-0"
            style={{
              background: `
                radial-gradient(circle at 18% 20%, rgba(20, 115, 230, 0.08) 0%, transparent 34%),
                radial-gradient(circle at 100% 0%, rgba(255, 122, 69, 0.08) 0%, transparent 26%)
              `,
            }}
          />

          <div className="relative z-10 flex min-h-0 w-full max-w-[31rem] flex-col">
            <div className="mb-4 flex items-center justify-between px-4 pt-4 sm:px-0 sm:pt-0 lg:hidden">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-accent shadow-[0_16px_28px_rgba(20,115,230,0.24)]">
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
                    <path d="M8 1.5a1 1 0 0 1 1 1v2a1 1 0 0 1-2 0v-2a1 1 0 0 1 1-1ZM14.5 7a1 1 0 0 1-1 1h-2a1 1 0 1 1 0-2h2a1 1 0 0 1 1 1ZM8 11.5a1 1 0 0 1 1 1v2a1 1 0 1 1-2 0v-2a1 1 0 0 1 1-1Z" fill="white"/>
                  </svg>
                </div>
                <div>
                  <p className="text-sm font-semibold tracking-[-0.02em] text-foreground">AxonVoice</p>
                  <p className="text-[0.68rem] text-muted">Operator access</p>
                </div>
              </div>
              <span className="rounded-full border border-line bg-white/70 px-3 py-1 text-[0.62rem] font-medium uppercase tracking-[0.16em] text-muted">
                Secure
              </span>
            </div>

            <div className="surface-card-strong flex min-h-0 max-h-[calc(100dvh-1.25rem)] flex-col overflow-hidden p-5 sm:max-h-[calc(100dvh-1.75rem)] sm:p-6 lg:max-h-[calc(100dvh-2.25rem)] lg:p-6">
              <div className="scrollbar-panel scrollbar-panel-light min-h-0 overflow-y-auto pr-1">
                {children}
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
